name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
  test:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
